
---

  - name: Upgrading system packages
    shell: zypper dist-upgrade -l -y
    register: upgrade
    tags: upgrade

  - name: Cleaning up zypper cache
    shell: zypper clean -a
    tags: upgrade

  - name: Rebooting
    shell: sleep 2 && shutdown -r now "Ansible reboot"
    ignore_errors: true
    async: 1
    poll: 0
    when: upgrade.rc == 0
    tags: upgrade

