
---

  - name: Upgrade OpenSUSE Tumbleweed
    block:
      - import_tasks: ./susetw/snapdel.yml
      - import_tasks: ./susetw/upgrade.yml
    when: ansible_distribution == 'openSUSE Tumbleweed'

  - name: Upgrade OpenSUSE Leap
    block:
      - import_tasks: ./suseleap/snapdel.yml
      - import_tasks: ./suseleap/update.yml
    when: ansible_distribution == 'openSUSE Leap'

  - name: Upgrade RedHat 
    import_tasks: ./redhat/update.yml
    when: ansible_os_family|lower == 'redhat'


