
---

  - name: Upgrade the OpenSUSE Linux systems
    import_tasks: ./upgrade/suse.yml
    when: ansible_os_family|lower == 'suse'

  - name: Upgrade the RedHat Linux systems
    import_tasks: ./upgrade/redhat.yml
    when: ansible_os_family|lower == 'redhat'

  - import_tasks: "reboot.yml"

